root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/server.exe ./cmd/server"
  bin = "./tmp/server.exe"
  include_ext = ["go"]
  exclude_dir = ["tmp", "uploads", "vendor"]
  delay = 500
  stop_on_error = true
  send_interrupt = true
  kill_delay = 500

[log]
  time = true

[misc]
  clean_on_exit = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"
