CREATE TABLE IF NOT EXISTS links (
 id UUID PRIMARY KEY,
 title VARCHAR(200) NOT NULL,
 url TEXT NOT NULL,
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
 updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
